### ISSUE TITLE
Realizar diagrama de clases

### ISSUE THREAD

**Issue by mayagato2008** [oscarnvg/TeamBlue#1]

**Comment by oscarnvg** [comment]
[AsignacionSalones.zip](https://github.com/oscarnvg/TeamBlue/files/7147884/AsignacionSalones.zip)

**Comment by oscarnvg** [comment]
[AsignacionSalones.zip](https://github.com/oscarnvg/TeamBlue/files/7147887/AsignacionSalones.zip)
Diagrama de clases Proyecto Asignación de Salones
